[plugin]
repository = "https://github.com/GrimmortalDread/NoQuestIcons.git"
commit = "b6071378e4d4dfb42a7497bd6483e7362e37ba57"
owners = ["GrimmortalDread"]
changelog = "v1.2.8 - Stable automation, resized icon, ready for DIP17 testing"
